<?php
/**
 * This script will generate an ActionForm instance using the
 * classname and properties supplied on the commandline.  It
 * will extend from studs.action.ActionForm unless another base 
 * action form is specified in the settings below.  All the accessor
 * methods will be generated for the properties supplied.
 *
 * The usage is as follows:
 *
 * php actionform_generator.php ClassName property1 property2 ...
 *
 * The following example generates a typical LoginForm class:
 *
 * php actionform_generator.php LoginForm username password rememberMe
 *
 * @author Timur Vafin
 * @author Dan Allen
 */

$baseActionForm = 'studs.action.ActionForm';
$baseActionFormName = preg_replace(';.*?([^\.]+)$;', '\\1', $baseActionForm);

$ACTION_FORM_SRC = <<<ACTION_FORM
<?php
import('$baseActionForm');

/* (non-Phpdoc)
 * Auto-generated by Studs action form generator.
 */
class %className% extends $baseActionFormName
{%propsDef%%propsSetGet%
	function &validate(&\$mapping, &\$request)
	{
		\$errors =& parent::validate(\$mapping, \$request);

		return \$errors;
	}
}
?>
ACTION_FORM;

$SET_GET = <<<SET_GET

	function set%Prop%(\$value)
	{
		\$this->%prop% = \$value;
	}
		
	function get%Prop%()
	{
		return \$this->%prop%;
	}

SET_GET;

$DEF_PROP = <<<DEF_PROP

	var \$%prop%;

DEF_PROP;

// remove file name from arguments
array_shift($argv);

// get class name
$className = array_shift($argv);

// collect uniq properties
$props = array();
foreach ($argv as $index => $arg)
{
	$props[$arg] = $arg;
}

// generate strings
$propsSetGetStr	= '';
$propsStr		= '';
foreach ($props as $prop)
{
	$propsStr .= strtr($DEF_PROP, array(
		'%prop%'	=> $prop,
	));

	$propsSetGetStr .= strtr($SET_GET, array(
		'%prop%'	=> $prop,
		'%Prop%'	=> ucfirst($prop),
	));
}


// format final source
$source = strtr($ACTION_FORM_SRC, array(
	'%propsDef%'		=> $propsStr,
	'%propsSetGet%'		=> $propsSetGetStr,
	'%className%'		=> $className,
));

// write file
write_source('./' . $className . '.php', $source);

function write_source($filepath, $source)
{
	$fp = fopen($filepath, 'w');
	fwrite($fp, $source);
	fclose($fp);
}
?>
